// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _01_DAL;

namespace _01_DAL.Migrations
{
    [DbContext(typeof(BD))]
    [Migration("20190912101804_migration_12_09_2019")]
    partial class migration_12_09_2019
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("_01_DAL.Empregado", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EMail");

                    b.Property<string>("Nome");

                    b.Property<int>("Numero_Empregado");

                    b.HasKey("ID");

                    b.ToTable("Empregados");
                });

            modelBuilder.Entity("_01_DAL.Fatura", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Data_Fatura");

                    b.Property<int>("ID_Empregado");

                    b.Property<double>("Preco_Final");

                    b.Property<int?>("ProdutoID");

                    b.HasKey("ID");

                    b.HasIndex("ID_Empregado");

                    b.HasIndex("ProdutoID");

                    b.ToTable("Faturas");
                });

            modelBuilder.Entity("_01_DAL.Linha_Fatura", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("FaturaID");

                    b.Property<int>("ID_Produto");

                    b.Property<double>("Preco_Produto");

                    b.Property<int>("Quantidade_Produto");

                    b.HasKey("ID");

                    b.HasIndex("FaturaID");

                    b.HasIndex("ID_Produto");

                    b.ToTable("Linhas_Fatura");
                });

            modelBuilder.Entity("_01_DAL.Produto", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao_Produto");

                    b.Property<int>("ID_Empregado");

                    b.Property<string>("Nome");

                    b.HasKey("ID");

                    b.HasIndex("ID_Empregado");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("_01_DAL.Fatura", b =>
                {
                    b.HasOne("_01_DAL.Empregado", "Empregado")
                        .WithMany("Lista_Faturas")
                        .HasForeignKey("ID_Empregado")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("_01_DAL.Produto")
                        .WithMany("Faturas")
                        .HasForeignKey("ProdutoID");
                });

            modelBuilder.Entity("_01_DAL.Linha_Fatura", b =>
                {
                    b.HasOne("_01_DAL.Fatura")
                        .WithMany("Lista_Linhas_Faturas")
                        .HasForeignKey("FaturaID");

                    b.HasOne("_01_DAL.Produto", "Produto")
                        .WithMany("Lista_Linhas_Faturas")
                        .HasForeignKey("ID_Produto")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("_01_DAL.Produto", b =>
                {
                    b.HasOne("_01_DAL.Empregado", "Empregado")
                        .WithMany("Lista_Produtos")
                        .HasForeignKey("ID_Empregado")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
